services:
  ide:
    image: ide:latest
    container_name: ide
    hostname: ide
    stdin_open: true
    tty: true
    volumes:
      - ${PWD}:/home/${USER_NAME:-me}/workdir
      - type: bind
        source: ${HOME}/.ssh
        target: /home/${USER_NAME:-me}/.ssh
        bind:
          create_host_path: false
      - type: bind
        source: ${HOME}/.gitconfig
        target: /home/${USER_NAME:-me}/.gitconfig
        bind:
          create_host_path: false
      - type: bind
        source: ${HOME}/.env
        target: /home/${USER_NAME:-me}/.env
        bind:
          create_host_path: false
      - type: bind
        source: ${HOME}/.netrc
        target: /home/${USER_NAME:-me}/.netrc
        bind:
          create_host_path: false
    build:
      context: .
      args:
        USER_NAME: ${USER_NAME:-me}
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
