[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.pylsp.config.pylsp]
plugins.ruff.enabled = true
plugins.black.enabled = true

[language-server.taplo]
config = {}

[[language]]
name = "json"
file-types = ["json"]
language-servers = ["vscode-json-language-server"]

[[language]]
name = "yaml"
file-types = ["yaml", "yml"]
language-servers = ["yaml-language-server"]
formatter = { command = "yamlfmt", args = ["-formatter", "indentless_arrays=true,retain_line_breaks=true", "-"] }

[[language]]
name = "toml"
file-types = ["toml"]
language-servers = ["taplo"]
formatter = { command = "taplo", args = ["fmt", "-"] }

[[language]]
name = "lua"
file-types = ["lua"]
language-servers = ["lua-language-server"]

[[language]]
name = "bash"
language-servers = ["bash-language-server"]
formatter = { command = "shfmt", args = ["-i=4", "-"] }
